# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
    open-pull-requests-limit: 1
    groups:
      cargo-all-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
      cargo-security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "node/"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
    open-pull-requests-limit: 1
    groups:
      npm-all-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
      npm-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
