version: '3.1'

services:

  postgres:
    image: postgres:${PG_VERSION:-13}
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./playpen/db/postgres_migration.sql:/docker-entrypoint-initdb.d/migration.sql
    ports:
      - 54321:5432

  mysql:
    image: mysql:5.6
    restart: always
    volumes:
      - ./playpen/db/mysql_migration_5_6.sql:/docker-entrypoint-initdb.d/mysql_migration.sql
    ports:
      - 33306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: sqlx-ts
