version: '3.1'

services:

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./playpen/db/postgres_migration.sql:/docker-entrypoint-initdb.d/migration.sql
    ports:
      - 54321:5432
