fn_single_line = true
force_multiline_blocks = true
format_code_in_doc_comments = true
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
imports_granularity = "Crate"
normalize_comments = false
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
report_fixme = "Always"
report_todo = "Never"
use_field_init_shorthand = true
use_try_shorthand = true
array_width = 60
