name: clippy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: [self-hosted, my-machine-2]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: test
        run: sysctl hw.model

      - name: hmm
        run: pwd

      - name: Run clippy
        run: cargo clippy

      - name: Run rustfmt
        run: cargo fmt -- --check
