on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: cross build

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
          - target: x86_64-unknown-linux-musl
          - target: x86_64-apple-darwin
    steps:
      - uses: actions/checkout@master
      - name: Compile
        uses: rust-build/rust-build.action@latest
        env:
          RUSTTARGET: ${{ matrix.target }}
