on: [push]

name: release

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build

      - name: Package
        shell: bash
        run: |
          ls target
