name: Install

on:
  push:
    branches: [ windows-installation ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Include all "Tier 1 with Host Tools" targets and "Tier 2 with Host Tools" targets for Windows and macOS,
        # excluding *-pc-windows-msvc, which requires cross-toolchains. Goal is one option per OS per architecture.
        # https://doc.rust-lang.org/rustc/platform-support.html
        # https://github.com/cross-rs/cross#supported-targets
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
        include:
          - os: ubuntu-latest
            shell: sh
          - os: ubuntu-latest
            shell: bash
          - os: macos-latest
            shell: sh
          - os: macos-latest
            shell: bash
          - os: windows-latest
            shell: sh
          - os: windows-latest
            shell: bash
          - os: windows-latest
            shell: pwsh
          - os: windows-latest
            shell: PowerShell
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install sqlx-ts
        shell: ${{ matrix.shell }}
        run: npm install -g sqlx-ts
      - name: run sqlx-ts help
        shell: ${{ matrix.shell }}
        run: sqlx-ts --help
      - name: run sqlx-ts version
        shell: ${{ matrix.shell }}
        run: sqlx-ts --version
