name: Node build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 12, 14, 15, 16, 17, 18, 19, 20 ]
    defaults:
      run:
        working-directory: ./node
    steps:
        - uses: actions/checkout@v3

        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node }}

        - name: install dependencies
          run: npm install --ignore-scripts

        - name: lint
          run: npm run lint

        - name: build
          run: npm run compile

        - name: test
          run: npm run test
