name: Node build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./node
    steps:
        - uses: actions/checkout@v2

        - name: Use Node.js
          uses: actions/setup-node@v2
          with:
            node-version: "lts/fermium"

        - name: install dependencies
          run: npm install --ignore-scripts

        - name: lint
          run: npm run lint

        - name: build
          run: npm run compile

        - name: test
          run: npm run test
