on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: release

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
          - target: x86_64-unknown-linux-musl
          - target: x86_64-apple-darwin
    steps:
      - name: Update repository cache
        run: sudo apt update -y
      - name: Install dependencies
        run: sudo apt-get install -y librust-libz-sys-dev
      - uses: actions/checkout@master
      - name: Compile
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }} --locked
