on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: release

jobs:
  build-release:
    name: release ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # - target: x86_64-pc-windows-gnu
          - build: linux
            os: ubuntu-20.04
            rust: stable
            target: x86_64-unknown-linux-musl
          - build: macos
            os: macos-12
            rust: stable
            target: x86_64-apple-darwin

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Install packages (Ubuntu)
        if: matrix.os == 'ubuntu-20.04'
        run: |
          ci/ubuntu-install-packages

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          profile: minimal
          override: true

      - name: Build release binary
        run: cargo build --verbose --release

      - name: check
        run: |
          ls target/
          ls target/${{ matrix.target }}