name: rust test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        db:
          - mysql: 8
          - mysql: 5.7
          - mysql: 5.6
          - postgres: 18
          - postgres: 17
          - postgres: 16
          - postgres: 15
          - postgres: 14
          - postgres: 13
          - postgres: 12

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: rustup toolchain install stable --profile minimal

      - uses: Swatinem/rust-cache@v2
        with:
          # To only cache runs from `master`:
          save-if: ${{ github.ref == 'refs/heads/master' }}
          # Specifies what to use as the backend providing cache
          # Can be set to either "github" or "buildjet"
          # default: "github"
          cache-provider: "github"

      - name: build docker-compose services for integration tests
        run: docker-compose -f docker-compose.yml up -d
        env:
          MYSQL_VERSION: ${{ matrix.db.mysql }}
          PG_VERSION: ${{ matrix.db.postgres }}

      - uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: '10' # for 10 seconds

      - name: Check the docker-compose services running
        run: docker ps -a

      - name: Run tests
        run: cargo test -- --test-threads=1
