name: rust test

on:
  push:
    branches: [ self-hosted-runner-experiment ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: [self-hosted, my-machine-1]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Check the docker-compose services running
        run: docker ps -a

      - name: Run tests
        run: cargo test -- --test-threads=1
