name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: build docker-compose services for integration tests
        run: docker-compose -f docker-compose.yml up -d

      - uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: '10' # for 10 seconds

      - name: Check the docker-compose services running
        run: docker ps -a

      - name: Run cargo-tarpaulin
          uses: actions-rs/tarpaulin@v0.1
          with:
            version: '0.25.2'
            args: '-- --test-threads 1'
      # - name: Install tarpaulin
      #   run: cargo install cargo-tarpaulin

      # - name: Run tests
      #   run: cargo tarpaulin --fail-under 83

  coverage:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: build docker-compose services for integration tests
        run: docker-compose -f docker-compose.yml up -d

      - uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: '10' # for 10 seconds

      - name: Check the docker-compose services running
        run: docker ps -a

      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run coverage
        run: cargo tarpaulin -o html -b --coveralls ${{ secrets.COVERALLS_KEY }}
